In [1]:
import os
import pandas as pd

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

In [33]:
df = pd.read_csv("final_nt_workflow/biob_nt_seqs.txt", delimiter="\t")

In [36]:
df = df.dropna()

In [39]:
df['biob_seq'] = df['biob_seq'].str.replace(" ", "")

/var/folders/6y/gt119tf53zv26yhf0ttb3dcr0000gn/T/ipykernel_96969/409210006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['biob_seq'] = df['biob_seq'].str.replace(" ", "")

In [43]:
Seq(df.loc[0,'biob_seq']).translate()

Seq('VTQATVTTQASADDVLTVAREQVLERGIGLSREQTLGVLRLADDRLEQLLELAH...TF*', HasStopCodon(ExtendedIUPACProtein(), '*'))

In [59]:
seqs = []

for i in df.index:
    seqs.append(SeqRecord(Seq(df.loc[i,'biob_seq']).translate(table=11), id=df.loc[i,'ssciname'], description=""))

In [60]:
seqs[:5]

[SeqRecord(seq=Seq('VTQATVTTQASADDVLTVAREQVLERGIGLSREQTLGVLRLADDRLEQLLELAH...TF*', HasStopCodon(ExtendedIUPACProtein(), '*')), id='Nocardia flavorosea NBRC 108225', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('MTQAPVTTDILATAREQVLERGEGLDREQTLEVLRLGDDRLEELLALAHEVRLR...TL*', HasStopCodon(ExtendedIUPACProtein(), '*')), id='Nocardia harenae NBRC 108248', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VTQVSTDILAVAREQVLAEGTGLSREQVLDVLHLPDDRLEELLAVAHEVRMTWC...TI*', HasStopCodon(ExtendedIUPACProtein(), '*')), id='Rhodococcus yunnanensis NBRC 103083', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VTQATVDTARDAQTSDDILAIAREQVLERGEPLDRDQVLAVLRLDDDRLTELLQ...TI*', HasStopCodon(ExtendedIUPACProtein(), '*')), id='Gordonia westfalica', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VTAAAERTGADRDSTGDSTDVLALAREQVLERGVGLDEARVLEILRLPDDRMPE...TL*', HasStopCodon(ExtendedIUPACProtein(), '*')), id='Actinophytocola xinjiangensis', name='<unknown name>', description='', dbxrefs=[])]

In [61]:


SeqIO.write(seqs, "biob_protein_sequences.fa", "fasta")

78

,ssciname,biob_seq
0,Nocardia flavorosea NBRC 108225,gtgacccaggccaccgtcaccactcaggcatccgcggacgatgtgc...
1,Nocardia harenae NBRC 108248,atgacccaggcacccgtcaccaccgacatactggcgactgcccgcg...
2,Rhodococcus yunnanensis NBRC 103083,gtgacacaggtatcgaccgacattctcgcggttgcccgcgaacagg...
3,Gordonia westfalica,gtgacacaggcaaccgtcgacaccgcccgcgacgcacagacgtccg...
4,Actinophytocola xinjiangensis,gtgaccgctgccgccgaacggaccggggctgaccgcgactcgacag...
...,...,...
75,Nocardia higoensis NBRC 100133,gtgacccaggcacccgtccagaccgacattctcgagatcgcgcgcg...
76,Sporichthya polymorpha DSM 43042,atgaccacgctcgaagaccgcccgctggcgaccgacccggccgacc...
77,Corynebacterium terpenotabidum Y-11,atgacggacatactcacgactgcgcgtacccgcgtccttgacgacg...
78,Corynebacterium argentoratense DSM 44202,atgagcacccccaccaccgaacagcccttagcccactcgtccgagg...
79,Frankia coriariae,gtgctggagcatggccaggggctctccaccgaacagacccttcagg...

In [26]:
a = pd.read_csv("23may2023/ncbi_taxid.txt", header=None)

In [27]:
a = a.transpose()

In [28]:
a[0] = a[0].str.strip("()")

In [29]:
a[['species', 'taxid']] = a[0].str.split(":", expand=True)[0].str.split(" - ", expand=True)

In [35]:
a['family'] = a['species'].str.split(expand=True)[0]

In [38]:
a[['taxid', 'species', 'family']].to_csv("subset50_taxid_annotations_21Jun.csv", index=False)

In [4]:
cols = ['sseqid', 'evalue', 'bitscore', 'pident', 'length', 'staxid', 'scomnames', 'ssciname', 'sblastnames', 'sseq']

a = pd.read_csv("23may2023/bspaONLY_blastn_out_subj_besthit_23may2023.tsv", delimiter="\t", names=cols)
b = pd.read_csv("23may2023/bspaONLY_blastn_out_taxid_limited_23may2023.tsv", delimiter="\t", names=cols)

In [5]:
df = pd.concat([a, b])

In [6]:
df.shape

(1163, 10)

In [7]:
df = df[df['length'] > 80].reset_index(drop=True)

In [8]:
# df['scomnames'].str.split(" ", expand=True)[0].value_counts()

In [9]:
df[['staxid', 'sseq']]

      staxid                                               sseq
0      83332  ATGGTGGAAATCGTGGCTGGAAAACAACGCGCTCCGGTCGCTGCCG...
1    1048245  ATGGTGGAAATCGTGGCTGGAAAACAACGCGCTCCGGTCGCTGCCG...
2     398694  GGTGGAGA-CGTGGCTGGAAAACAAGACGCTCCGGTCACTGCCGGC...
3     627089  GGACATCATGGCTGGAAACCTGGGCGCTCCCGTCGCCGCCGGCGTC...
4      28445  ATCGTGGTTGCAAACCTGGGCGCTCCGGTCGGTGCCGGGGTGTACA...
..       ...                                                ...
502   135487  TGGGCCTGGAGCCGCCGCGGTTCTGTGAACACTGCGGGCGCAGGAT...
503    37330  TGGGCCTGGAACCGCCGCGTTACTGCGAGCACTGCGGCCGCCGGAT...
504    37331  GGCCTCGATCCACCCCGGTACTGCACGGCGTGCGGGCGGCGGATGG...
505  2736640  CTGGAACCGCCGCGGTACTGCGCCGACTGCGCGCGGCGGATGGTCG...
506    35755  TGTGGCCGTCGGATGGTCGTTCAGGTGCGCCCGGATGGTTGGTTGG...

[507 rows x 2 columns]

In [10]:
df['genus'] = df['ssciname'].str.split(" ", expand=True)[0]

In [212]:
df[['staxid', 'genus']].to_csv("23may2023/blastn_genus_names.csv", index=False)

In [228]:
a = "(280293:1.55663,2879464:0.0796147,(263849:0.15259,((1691570:0.0669446,(((((243061:0.189557,185642:0.261721)1:0.0407831,(886343:0.211199,((398694:0.0710365,((1045776:0.802085,2761101:0.5893)1:0.453888,1848329:0.602117)1:0.0829276)1:0.0506478,((37331:0.45267,1777:0.176606)1:1.9044e-06,1778:0.133212)1:0.0556167)1:0.0216464)1:0.0625773)1:0.0171702,((((((2545757:0.454726,2835306:0.342448)1:0.090141,300028:0.275386)1:0.0830528,1286180:0.429791)1:0.0564859,(1801:0.275965,(1771:0.389391,((443218:0.416917,35755:0.688791)1:2.0787e-06,1123258:0.181968)1:0.0970638)1:0.0726234)1:0.0369427)1:0.0243792,((683150:0.819267,370526:0.0605584)1:0.0901517,120959:0.211929)1:0.0358172)1:0.0601427,1387982:0.364283)1:0.0931764)1:0.0654383,((1077974:0.301386,521096:0.397605)1:0.00870889,(158898:0.191642,2420509:0.537106)1:0.20787)1:0.0454791)1:0.0729125,(((1220583:0.33338,((((((108486:0.452036,558173:0.289397)1:0.264035,(2724524:0.0950066,(83302:0.443952,1677852:0.368531)1:0.234131)1:2.5725e-06)1:0.14658,((547056:0.158138,1200352:0.598752)1:0.0181058,(1586287:0.245378,33919:0.42773)1:0.0642146)1:0.0328754)1:0.11181,(1970234:0.0767137,(543632:0.463579,1048339:0.493064)1:0.116263)1:2.1356e-06)1:0.0897763,1686286:0.11062)1:0.132298,391736:0.409049)1:0.0187591)1:0.0413319,2895283:0.26546)1:0.0888721,196164:0.287543)1:0.0450974)1:0.164241)1:0.0391856,(1210064:0.174459,452863:0.675299)1:0.0171338)1:0.298822)1:0.0591849)"

In [229]:
name_dict = dict(zip(df['staxid'].astype(str).tolist(), df['scomnames'].tolist()))

In [232]:
for key in name_dict.keys():
    a = a.replace(key, "'{}'".format(name_dict[key]))

In [233]:
a

"('Catenulispora rubra':1.55663,'Rhodococcus yananensis':0.0796147,('Rhodococcus phenolicus':0.15259,(('Nocardia rhizosphaerihabitans':0.0669446,((((('Mycobacterium sherrisii':0.189557,'Mycobacterium parmense':0.261721)1:0.0407831,('Mycobacterium spongiae':0.211199,(('Mycobacterium shinjukuense':0.0710365,(('Kutzneria buriramensis':0.802085,'Nocardioides luti':0.5893)1:0.453888,'Nonomuraea diastatica':0.602117)1:0.0829276)1:0.0506478,(('Pseudonocardia petroleophila':0.45267,'Mycobacterium gastri':0.176606)1:1.9044e-06,'Mycobacterium gordonae':0.133212)1:0.0556167)1:0.0216464)1:0.0625773)1:0.0171702,(((((('Prescottella subtropica':0.454726,'Mycolicibacter acidiphilus':0.342448)1:0.090141,'Rhodococcus triatomae':0.275386)1:0.0830528,'Mycolicibacterium sediminis':0.429791)1:0.0564859,('Mycobacterium diernhoferi':0.275965,('Mycolicibacterium phlei':0.389391,(('Hoyosella subflava DQS3-9A1':0.416917,'Corynebacterium kutscheri':0.688791)1:2.0787e-06,'Smaragdicoccus niigatensis DSM 44881 = NBRC 103563':0.181968)1:0.0970638)1:0.0726234)1:0.0369427)1:0.0243792,(('Arthrobacter nitrophenolicus':0.819267,'Mycolicibacterium rutilum':0.0605584)1:0.0901517,'Mycobacterium kubicae':0.211929)1:0.0358172)1:0.0601427,'Tomitella cavernea':0.364283)1:0.0931764)1:0.0654383,(('Gordonia effusa NBRC 100432':0.301386,'Tsukamurella paurometabola DSM 20162':0.397605)1:0.00870889,('Gordonia westfalica':0.191642,'Gordonia insulae':0.537106)1:0.20787)1:0.0454791)1:0.0729125,((('Gordonia aichiensis NBRC 108223':0.33338,(((((('Corynebacterium falsenii':0.452036,'Corynebacterium doosanense CAU 212 = DSM 45436':0.289397)1:0.264035,('Amycolatopsis acididurans':0.0950066,('Microbispora corallina':0.443952,'Microbispora camponoti':0.368531)1:0.234131)1:2.5725e-06)1:0.14658,(('Actinokineospora baliensis':0.158138,'Corynebacterium terpenotabidum Y-11':0.598752)1:0.0181058,('Lentzea guizhouensis':0.245378,'Saccharothrix coeruleofusca':0.42773)1:0.0642146)1:0.0328754)1:0.11181,('Tsukamurella ocularis':0.0767137,('Actinoplanes subtropicus':0.463579,'Sporichthya polymorpha DSM 43042':0.493064)1:0.116263)1:2.1356e-06)1:0.0897763,'Corynebacterium phoceense':0.11062)1:0.132298,'Williamsia serinedens':0.409049)1:0.0187591)1:0.0413319,'Mycolicibacterium lacusdiani':0.26546)1:0.0888721,'Corynebacterium efficiens YS-314':0.287543)1:0.0450974)1:0.164241)1:0.0391856,('Nocardia altamirensis NBRC 108246':0.174459,'Pseudarthrobacter chlorophenolicus A6':0.675299)1:0.0171338)1:0.298822)1:0.0591849)"

In [238]:
seqs = []


    
for record in SeqIO.parse("23may2023/bspa_blast_hit_23May_muscle.mfa.fasta", "fasta"):
    
    seqs.append(record)

In [243]:
for seq in seqs:
    seq.id = name_dict[seq.id]

In [245]:
seqs


SeqIO.write(seqs, "23may2023/bspa_blast_hit_23May_muscle_RENAME.mfa.fasta", "fasta")

484

In [248]:
a.split("(")

['',
 "'Catenulispora rubra':1.55663,'Rhodococcus yananensis':0.0796147,",
 "'Rhodococcus phenolicus':0.15259,",
 '',
 "'Nocardia rhizosphaerihabitans':0.0669446,",
 '',
 '',
 '',
 '',
 "'Mycobacterium sherrisii':0.189557,'Mycobacterium parmense':0.261721)1:0.0407831,",
 "'Mycobacterium spongiae':0.211199,",
 '',
 "'Mycobacterium shinjukuense':0.0710365,",
 '',
 "'Kutzneria buriramensis':0.802085,'Nocardioides luti':0.5893)1:0.453888,'Nonomuraea diastatica':0.602117)1:0.0829276)1:0.0506478,",
 '',
 "'Pseudonocardia petroleophila':0.45267,'Mycobacterium gastri':0.176606)1:1.9044e-06,'Mycobacterium gordonae':0.133212)1:0.0556167)1:0.0216464)1:0.0625773)1:0.0171702,",
 '',
 '',
 '',
 '',
 '',
 "'Prescottella subtropica':0.454726,'Mycolicibacter acidiphilus':0.342448)1:0.090141,'Rhodococcus triatomae':0.275386)1:0.0830528,'Mycolicibacterium sediminis':0.429791)1:0.0564859,",
 "'Mycobacterium diernhoferi':0.275965,",
 "'Mycolicibacterium phlei':0.389391,",
 '',
 "'Hoyosella subflava DQS3-9A1':0.416917,'Corynebacterium kutscheri':0.688791)1:2.0787e-06,'Smaragdicoccus niigatensis DSM 44881 = NBRC 103563':0.181968)1:0.0970638)1:0.0726234)1:0.0369427)1:0.0243792,",
 '',
 "'Arthrobacter nitrophenolicus':0.819267,'Mycolicibacterium rutilum':0.0605584)1:0.0901517,'Mycobacterium kubicae':0.211929)1:0.0358172)1:0.0601427,'Tomitella cavernea':0.364283)1:0.0931764)1:0.0654383,",
 '',
 "'Gordonia effusa NBRC 100432':0.301386,'Tsukamurella paurometabola DSM 20162':0.397605)1:0.00870889,",
 "'Gordonia westfalica':0.191642,'Gordonia insulae':0.537106)1:0.20787)1:0.0454791)1:0.0729125,",
 '',
 '',
 "'Gordonia aichiensis NBRC 108223':0.33338,",
 '',
 '',
 '',
 '',
 '',
 "'Corynebacterium falsenii':0.452036,'Corynebacterium doosanense CAU 212 = DSM 45436':0.289397)1:0.264035,",
 "'Amycolatopsis acididurans':0.0950066,",
 "'Microbispora corallina':0.443952,'Microbispora camponoti':0.368531)1:0.234131)1:2.5725e-06)1:0.14658,",
 '',
 "'Actinokineospora baliensis':0.158138,'Corynebacterium terpenotabidum Y-11':0.598752)1:0.0181058,",
 "'Lentzea guizhouensis':0.245378,'Saccharothrix coeruleofusca':0.42773)1:0.0642146)1:0.0328754)1:0.11181,",
 "'Tsukamurella ocularis':0.0767137,",
 "'Actinoplanes subtropicus':0.463579,'Sporichthya polymorpha DSM 43042':0.493064)1:0.116263)1:2.1356e-06)1:0.0897763,'Corynebacterium phoceense':0.11062)1:0.132298,'Williamsia serinedens':0.409049)1:0.0187591)1:0.0413319,'Mycolicibacterium lacusdiani':0.26546)1:0.0888721,'Corynebacterium efficiens YS-314':0.287543)1:0.0450974)1:0.164241)1:0.0391856,",
 "'Nocardia altamirensis NBRC 108246':0.174459,'Pseudarthrobacter chlorophenolicus A6':0.675299)1:0.0171338)1:0.298822)1:0.0591849)"]

In [246]:
seqs

[SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Catenulispora rubra', name='280293', description='280293', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Kutzneria buriramensis', name='1045776', description='1045776', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium silvaticum', name='2320431', description='2320431', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium meridianum', name='2765363', description='2765363', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium antarcticum', name='2800405', description='2800405', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium aquilae DSM 44791', name='1431546', description='1431546', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium deserti GIMN1.010', name='931089', description='931089', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium falsenii', name='108486', description='108486', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Arthrobacter nitrophenolicus', name='683150', description='683150', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Nocardioides luti', name='2761101', description='2761101', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Nonomuraea diastatica', name='1848329', description='1848329', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Pseudarthrobacter chlorophenolicus A6', name='452863', description='452863', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Luteipulveratus mongoliensis', name='571913', description='571913', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium argentoratense DSM 44202', name='1348662', description='1348662', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Williamsia serinedens', name='391736', description='391736', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacter acidiphilus', name='2835306', description='2835306', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacter terrae', name='1788', description='1788', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Tsukamurella paurometabola DSM 20162', name='521096', description='521096', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTAGCCGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides salmoniphilum', name='404941', description='404941', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCCGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='[Mycobacterium] stephanolepidis', name='1520670', description='1520670', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCCGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides chelonae CCUG 47445', name='1460372', description='1460372', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCTGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides saopaulense', name='1578165', description='1578165', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCTGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides abscessus', name='36809', description='36809', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCTGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides franklinii', name='948102', description='948102', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGCTGCCGGTAAGTAC...---', SingleLetterAlphabet()), id='Mycobacteroides immunogenum', name='83262', description='83262', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Rhodococcus yunnanensis NBRC 103083', name='1219029', description='1219029', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium pacaense', name='1816684', description='1816684', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium gallinarum', name='2762214', description='2762214', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium efficiens YS-314', name='196164', description='196164', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------------------------TAC...---', SingleLetterAlphabet()), id='Hoyosella subflava DQS3-9A1', name='443218', description='443218', dbxrefs=[]),
 SeqRecord(seq=Seq('----------------------------GCGCTCCGGTTAGTGCCGGTGGCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium spongiae', name='886343', description='886343', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium doosanense CAU 212 = DSM 45436', name='558173', description='558173', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium pseudodiphtheriticum DSM 44287', name='1121368', description='1121368', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGTGCCGGTGTCTTC...TGA', SingleLetterAlphabet()), id='Mycobacterium frederiksbergense', name='117567', description='117567', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCGCCGGTCGGCGCGGGCGTCTAT...---', SingleLetterAlphabet()), id='Candidatus Mycobacterium methanotrophicum', name='2943498', description='2943498', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCCCCGGTGGGCGCCGGGGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacillus trivialis', name='1798', description='1798', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCCCCGGTCGGTGCGGGTGACTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium aurum', name='1791', description='1791', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCTCCCGTCGGCGCAGGGGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium xanthum', name='2796469', description='2796469', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGCGCAGGCGTTTAC...TGA', SingleLetterAlphabet()), id='Mycolicibacterium wolinskyi', name='59750', description='59750', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCCGTCGGTGCAGGCGTCTAC...---', SingleLetterAlphabet()), id='Mycobacterium goodii', name='134601', description='134601', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGTGCCGGCGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium smegmatis', name='1772', description='1772', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCCCCGGTCGGGGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium talmoniae', name='1858794', description='1858794', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGGGCCGGGGTGTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium cosmeticum', name='258533', description='258533', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCTCCCGTCGGGGCCGGGGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium canariasense', name='228230', description='228230', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacterium parafortuitum', name='39692', description='39692', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCACCGGTCGGTGCGGGCGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium vaccae 95051', name='1354275', description='1354275', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacterium iranicum', name='912594', description='912594', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacterium fallax', name='1793', description='1793', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...T--', SingleLetterAlphabet()), id='Mycolicibacterium insubricum', name='444597', description='444597', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycolicibacterium brumae', name='85968', description='85968', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...TGA', SingleLetterAlphabet()), id='Mycolicibacterium chitae', name='1792', description='1792', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGCGCGGGCGCCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium gilvum Spyr1', name='278137', description='278137', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCGCCCGTCGGTGCCGGCGTCTAC...---', SingleLetterAlphabet()), id='Candidatus Mycolicibacterium alkanivorans', name='2954114', description='2954114', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTCGGTGCGGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium fragae', name='1260918', description='1260918', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCTCCGGTCGGCGCGGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium noviomagense', name='459858', description='459858', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTGAGTGCCGGGATCTAC...---', SingleLetterAlphabet()), id='Mycobacterium pallens', name='370524', description='370524', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTGAGTGCCGGGGTCTAC...TGA', SingleLetterAlphabet()), id='Mycolicibacterium rhodesiae', name='36814', description='36814', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTGGGTGCCGGCGTTTAC...TGA', SingleLetterAlphabet()), id='Mycolicibacterium aromaticivorans JS19b1 = JCM 16368', name='1440774', description='1440774', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTGAGTGCCGGGGTCTAC...TGA', SingleLetterAlphabet()), id='Mycolicibacterium aichiense', name='1799', description='1799', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCCGTCGGTGCCGGGGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium helvum', name='1534349', description='1534349', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTCGGTGCCGGGATCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium sarraceniae', name='1534348', description='1534348', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...TGA', SingleLetterAlphabet()), id='Mycolicibacterium litorale', name='758802', description='758802', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------CGCACCGGTCGGTGCCGGGGTCTAC...---', SingleLetterAlphabet()), id='Mycolicibacterium sphagni', name='1786', description='1786', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------------------------------------------------C...TGA', SingleLetterAlphabet()), id='Mycolicibacterium monacense', name='85693', description='85693', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Nocardia harenae NBRC 108248', name='1210074', description='1210074', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Skermania piniformis', name='39122', description='39122', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Prescottella subtropica', name='2545757', description='2545757', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTCGGCGCGGGGGTCTTC...---', SingleLetterAlphabet()), id='Mycobacterium pyrenivorans', name='187102', description='187102', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...TGA', SingleLetterAlphabet()), id='Mycobacterium shimoidei', name='29313', description='29313', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCCCCGATCGGCGCCGGCATCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium kyorinense', name='487514', description='487514', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCCCCGATCGGAGCCGGTGTGTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium celatum', name='28045', description='28045', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCCCCGATCGGAGCCGCTGTGTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium branderi', name='43348', description='43348', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Rhodococcus triatomae', name='300028', description='300028', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Smaragdicoccus niigatensis DSM 44881 = NBRC 103563', name='1123258', description='1123258', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Gordonia insulae', name='2420509', description='2420509', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Corynebacterium kutscheri', name='35755', description='35755', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Pseudonocardia petroleophila', name='37331', description='37331', dbxrefs=[]),
 SeqRecord(seq=Seq('-----GGACACCATGGCTGGAAACCTGGGCGCTCCCGTCGCCGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium riyadhense', name='486698', description='486698', dbxrefs=[]),
 SeqRecord(seq=Seq('---GTCGAAAACGTGGCTGGAAAACTGGGCGCTCCGGTGGCCGCCGGCGTCTAT...TGA', SingleLetterAlphabet()), id='Mycobacterium angelicum', name='470074', description='470074', dbxrefs=[]),
 SeqRecord(seq=Seq('----GTCGAAACGTGGCTGGAAAACTGGGCGCTCCGGTGGCCGCCGGCGTTTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium szulgai', name='1787', description='1787', dbxrefs=[]),
 SeqRecord(seq=Seq('--------------------------------TCCGGTGAGTGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium basiliense', name='2094119', description='2094119', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGGTCACTGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium ulcerans', name='1809', description='1809', dbxrefs=[]),
 SeqRecord(seq=Seq('--------------------------------TCCGGTCACTGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium shottsii', name='133549', description='133549', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGGTCACTGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium marinum', name='1781', description='1781', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGGTCACTGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium pseudoshottsii JCM 15466', name='1136880', description='1136880', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...TGA', SingleLetterAlphabet()), id='Mycobacterium leprae', name='1769', description='1769', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...TGA', SingleLetterAlphabet()), id='Mycobacterium lepromatosis', name='480418', description='480418', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGATTGGTGCGGGCGTCTAT...TGA', SingleLetterAlphabet()), id='Mycobacterium haemophilum DSM 44634', name='1202450', description='1202450', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGATCGGTGCGGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium uberis', name='2162698', description='2162698', dbxrefs=[]),
 SeqRecord(seq=Seq('---------------------------------CCGGTGGGAGCCGGGATCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium decipiens', name='1430326', description='1430326', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Tsukamurella pseudospumae', name='239498', description='239498', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Tsukamurella conjunctivitidis', name='2592068', description='2592068', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Tsukamurella ocularis', name='1970234', description='1970234', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Tsukamurella asaccharolytica', name='2592067', description='2592067', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------GCTCCGGTCGGGGCCGGCGCATAC...TGA', SingleLetterAlphabet()), id='Mycobacterium gordonae', name='1778', description='1778', dbxrefs=[]),
 SeqRecord(seq=Seq('-----------CGTGGCGGGAAATCTGGGCGCTCCGGTCGGAGCCGGCGTCTAC...---', SingleLetterAlphabet()), id='Mycobacterium paragordonae', name='1389713', description='1389713', dbxrefs=[]),
 SeqRecord(seq=Seq('----------------------------GCGCTGCGGTCAGCGCCGGTGTGTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium saskatchewanense', name='220927', description='220927', dbxrefs=[]),
 SeqRecord(seq=Seq('--GGGGGAAGTCGTGGTTCGCGATCTGGGCGCTCCGGTCTCCGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium parmense', name='185642', description='185642', dbxrefs=[]),
 SeqRecord(seq=Seq('------------------------------------------------------...---', SingleLetterAlphabet()), id='Mycobacterium palauense', name='2034511', description='2034511', dbxrefs=[]),
 SeqRecord(seq=Seq('----------------------------GCGCGCCGGTCGGCGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium numidiamassiliense', name='1841861', description='1841861', dbxrefs=[]),
 SeqRecord(seq=Seq('----------------------------GCGCTCCGGTCGGCGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium montefiorense', name='154654', description='154654', dbxrefs=[]),
 SeqRecord(seq=Seq('-GGTTGGAATCTGTGGTTGGAGATCTGGGTGCTCCGGTCAGCGCCGGCATCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium florentinum', name='292462', description='292462', dbxrefs=[]),
 SeqRecord(seq=Seq('----------------------------GCGCTCCGGTCAGCGCTGGCGTCTAT...TGA', SingleLetterAlphabet()), id='Mycobacterium lentiflavum', name='141349', description='141349', dbxrefs=[]),
 SeqRecord(seq=Seq('------------GTGGTTGGAGATCTGGGCGCTCCCGTCAGCGCCGGCGTCTAC...TGA', SingleLetterAlphabet()), id='Mycobacterium ahvazicum', name='1964395', description='1964395', dbxrefs=[]),

In [234]:
name_dict

{'83332': 'Mycobacterium tuberculosis H37Rv',
 '1048245': 'Mycobacterium canettii CIPT 140010059',
 '398694': 'Mycobacterium shinjukuense',
 '28445': 'Mycobacterium intermedium',
 '1273442': 'Mycobacterium bourgelatii',
 '486698': 'Mycobacterium riyadhense',
 '470074': 'Mycobacterium angelicum',
 '1787': 'Mycobacterium szulgai',
 '2094119': 'Mycobacterium basiliense',
 '1389713': 'Mycobacterium paragordonae',
 '1778': 'Mycobacterium gordonae',
 '1809': 'Mycobacterium ulcerans',
 '1408452': 'Mycobacterium genavense ATCC 51234',
 '439334': 'Mycobacterium avium subsp. hominissuis',
 '169765': 'Mycobacterium lacus',
 '133549': 'Mycobacterium shottsii',
 '1781': 'Mycobacterium marinum',
 '1136880': 'Mycobacterium pseudoshottsii JCM 15466',
 '1430326': 'Mycobacterium decipiens',
 '47839': 'Mycobacterium triplex',
 '53378': 'Mycobacterium paraffinicum',
 '53376': 'Mycobacterium heidelbergense',
 '33895': 'Mycobacterium interjectum',
 '701042': 'Mycobacterium marseillense',
 '244292': 'Mycobacterium nebraskense',
 '470076': 'Mycobacterium stomatepiae',
 '1260918': 'Mycobacterium fragae',
 '44467': 'Mycobacterium tilburgii',
 '1777': 'Mycobacterium gastri',
 '1767': 'Mycobacterium intracellulare',
 '1138383': 'Mycobacterium paraintracellulare',
 '525368': 'Mycobacterium parascrofulaceum ATCC BAA-614',
 '220927': 'Mycobacterium saskatchewanense',
 '243061': 'Mycobacterium sherrisii',
 '1841861': 'Mycobacterium numidiamassiliense',
 '701043': 'Mycobacterium timonense',
 '1841859': 'Mycobacterium terramassiliense',
 '701041': 'Mycobacterium bouchedurhonense',
 '1964395': 'Mycobacterium ahvazicum',
 '761804': 'Mycobacterium europaeum',
 '1202450': 'Mycobacterium haemophilum DSM 44634',
 '547163': 'Mycobacterium vulneris',
 '767916': 'Mycobacterium paraense',
 '1783': 'Mycobacterium scrofulaceum',
 '154654': 'Mycobacterium montefiorense',
 '2943498': 'Candidatus Mycobacterium methanotrophicum',
 '2341083': 'Mycobacterium innocens',
 '2738409': 'Mycobacterium ostraviense',
 '1265311': 'Mycobacterium arosiense ATCC BAA-1401 = DSM 45069',
 '1041522': 'Mycobacterium colombiense CECT 3035',
 '1784': 'Mycobacterium simiae',
 '292462': 'Mycobacterium florentinum',
 '560555': 'Mycobacterium mantenii',
 '2775496': 'Mycobacterium senriense',
 '84962': 'Mycobacterium botniense',
 '153971': 'Mycobacterium palustre',
 '120959': 'Mycobacterium kubicae',
 '1487726': 'Mycobacterium persicum',
 '141349': 'Mycobacterium lentiflavum',
 '1719132': 'Mycobacterium vicinigordonae',
 '557599': 'Mycobacterium kansasii ATCC 12478',
 '2162698': 'Mycobacterium uberis',
 '722731': 'Mycobacterium shigaense',
 '1841860': 'Mycobacterium rhizamassiliense',
 '590652': 'Mycobacterium paraseoulense',
 '2592811': 'Mycobacterium helveticum',
 '886343': 'Mycobacterium spongiae',
 '185642': 'Mycobacterium parmense',
 '459858': 'Mycobacterium noviomagense',
 '28045': 'Mycobacterium celatum',
 '56425': 'Mycobacterium bohemicum',
 '43348': 'Mycobacterium branderi',
 '324058': 'Mycobacterium alsense',
 '1354275': 'Mycolicibacterium vaccae 95051',
 '1772': 'Mycolicibacterium smegmatis',
 '487514': 'Mycobacterium kyorinense',
 '258533': 'Mycolicibacterium cosmeticum',
 '564198': 'Mycolicibacterium bacteremicum',
 '1789': 'Mycobacterium xenopi',
 '216929': 'Mycolicibacterium psychrotolerans',
 '1800': 'Mycolicibacterium chubuense',
 '2796469': 'Mycolicibacterium xanthum',
 '2212479': 'Mycobacterium kyogaense',
 '117567': 'Mycobacterium frederiksbergense',
 '59750': 'Mycolicibacterium wolinskyi',
 '577492': 'Mycobacterium paraterrae',
 '1807': 'Mycolicibacterium obuense',
 '1782': 'Mycolicibacter nonchromogenicus',
 '110505': 'Mycobacterium heckeshornense',
 '1858794': 'Mycobacterium talmoniae',
 '1769': 'Mycobacterium leprae',
 '319707': 'Mycolicibacterium aubagnense',
 '1440774': 'Mycolicibacterium aromaticivorans JS19b1 = JCM 16368',
 '146018': 'Mycolicibacterium neworleansense',
 '318424': 'Mycobacterium rufum',
 '1534349': 'Mycolicibacterium helvum',
 '2954114': 'Candidatus Mycolicibacterium alkanivorans',
 '1797': 'Mycolicibacterium thermoresistibile',
 '1791': 'Mycolicibacterium aurum',
 '158898': 'Gordonia westfalica',
 '43304': 'Mycolicibacterium peregrinum',
 '228909': 'Mycobacterium hackensackense',
 '126673': 'Mycobacterium doricum',
 '228230': 'Mycolicibacterium canariasense',
 '1801': 'Mycobacterium diernhoferi',
 '1108812': 'Mycolicibacter longobardus',
 '1108045': 'Gordonia rhizosphera NBRC 16068',
 '39693': 'Mycobacterium porcinum',
 '2736649': 'Mycolicibacterium mengxianglii',
 '67081': 'Mycolicibacterium alvei',
 '2487344': 'Mycolicibacterium nivoides',
 '146021': 'Mycolicibacterium houstonense',
 '134601': 'Mycobacterium goodii',
 '278137': 'Mycolicibacterium gilvum Spyr1',
 '1210074': 'Nocardia harenae NBRC 108248',
 '1286180': 'Mycolicibacterium sediminis',
 '1799': 'Mycolicibacterium aichiense',
 '1534348': 'Mycolicibacterium sarraceniae',
 '451644': 'Mycolicibacterium conceptionense',
 '1053547': 'Gordonia alkaliphila',
 '1303685': 'Mycolicibacterium chlorophenolicum JCM 7439 = NBRC 15527',
 '1073574': 'Gordonia araii NBRC 100433',
 '354243': 'Mycolicibacter kumamotonensis',
 '2420509': 'Gordonia insulae',
 '319706': 'Mycolicibacterium phocaicum',
 '431269': 'Mycolicibacterium setense',
 '342002': 'Mycolicibacter arupensis',
 '1288388': 'Mycolicibacter algericus',
 '2492438': 'Mycobacterium novum',
 '191292': 'Rhodococcus aetherivorans',
 '370524': 'Mycobacterium pallens',
 '1908205': 'Mycobacterium syngnathidarum',
 '480418': 'Mycobacterium lepromatosis',
 '875328': 'Mycolicibacter sinensis',
 '2725283': 'Gordonia asplenii',
 '2487364': 'Rhodococcus xishaensis',
 '29313': 'Mycobacterium shimoidei',
 '39695': 'Mycolicibacterium tokaiense',
 '36822': 'Gordonia rubripertincta',
 '182220': 'Mycolicibacterium murale',
 '589162': 'Gordonia crocea',
 '1118379': 'Mycolicibacter minnesotensis',
 '1798': 'Mycolicibacillus trivialis',
 '1641992': 'Mycolicibacterium lutetiense',
 '1776': 'Mycolicibacterium flavescens',
 '1795032': 'Mycobacterium virginiense',
 '85693': 'Mycolicibacterium monacense',
 '28047': 'Mycolicibacterium confluentis',
 '2055': 'Gordonia terrae',
 '1786': 'Mycolicibacterium sphagni',
 '350058': 'Mycolicibacterium vanbaalenii PYR-1',
 '1344003': 'Williamsia sterculiae',
 '370526': 'Mycolicibacterium rutilum',
 '59813': 'Mycolicibacterium novocastrense',
 '912594': 'Mycolicibacterium iranicum',
 '1206733': 'Nocardia niigatensis NBRC 100131',
 '386913': 'Mycolicibacter senuensis',
 '1701090': 'Gordonia hongkongensis',
 '89053': 'Gordonia amicalis',
 '2487352': 'Rhodococcus spongiicola',
 '187102': 'Mycobacterium pyrenivorans',
 '1226753': 'Mycolicibacterium mucogenicum DSM 44124',
 '1792835': 'Mycolicibacter icosiumassiliensis',
 '2665643': 'Gordonia mangrovi',
 '417102': 'Gordonia lacunae',
 '39687': 'Mycolicibacterium austroafricanum',
 '1644129': 'Prescottella agglutinans',
 '2048550': 'Mycobacterium lehmannii',
 '1208314': 'Gordonia namibiensis NBRC 108229',
 '1796': 'Mycobacterium senegalense',
 '758802': 'Mycolicibacterium litorale',
 '39694': 'Mycolicibacterium poriferae',
 '249058': 'Gordonia otitidis',
 '29314': 'Mycolicibacter hiberniae',
 '404941': 'Mycobacteroides salmoniphilum',
 '84096': 'Gordonia alkanivorans',
 '319709': 'Mycobacterium barrassiae',
 '1829': 'Rhodococcus rhodochrous',
 '258505': 'Mycolicibacterium fluoranthenivorans',
 '132919': 'Rhodococcus jostii',
 '444597': 'Mycolicibacterium insubricum',
 '1725': 'Corynebacterium xerosis',
 '1210066': 'Nocardia amamiensis NBRC 102102',
 '1802': 'Mycolicibacterium farcinogenes',
 '134034': 'Corynebacterium freneyi',
 '2382165': 'Nocardia yunnanensis',
 '2048551': 'Mycobacterium neumannii',
 '1566885': 'Mycolicibacterium komanii',
 '948102': 'Mycobacteroides franklinii',
 '2895283': 'Mycolicibacterium lacusdiani',
 '1793': 'Mycolicibacterium fallax',
 '38310': 'Rhodococcus coprophilus',
 '1779': 'Mycolicibacterium komossense',
 '1223545': 'Gordonia soli NBRC 108243',
 '146017': 'Mycolicibacterium boenickei',
 '53462': 'Mycolicibacterium mageritense',
 '1830': 'Rhodococcus ruber',
 '480035': 'Nocardia wallacei',
 '1435356': 'Rhodococcus pyridinivorans SB3094',
 '2055889': 'Nocardia tengchongensis',
 '43767': 'Prescottella equi',
 '2675850': 'Nocardia aurantiaca',
 '1077974': 'Gordonia effusa NBRC 100432',
 '36821': 'Gordonia amarae',
 '2831662': 'Gordonia pseudamarae',
 '36814': 'Mycolicibacterium rhodesiae',
 '228006': 'Nocardia tenerifensis',
 '526226': 'Gordonia bronchialis DSM 43247',
 '1755582': 'Hoyosella rhizosphaerae',
 '1223547': 'Nocardia rhamnosiphila NBRC 108938',
 '1223548': 'Nocardia mikamii NBRC 108933',
 '322609': 'Williamsia marianensis',
 '152142': 'Mycobacterium holsaticum',
 '468556': 'Jongsikchunia kroppenstedtii DSM 45133',
 '882452': 'Williamsia limnetica',
 '1206737': 'Nocardia pneumoniae NBRC 100136',
 '644548': 'Gordonia neofelifaecis NRRL B-59395',
 '1210091': 'Nocardia ninae NBRC 108245',
 '1210093': 'Nocardia pseudovaccinii NBRC 100343',
 '1206741': 'Nocardia concava NBRC 100430',
 '1286181': 'Mycolicibacterium arabiense',
 '36811': 'Mycolicibacterium agri',
 '188915': 'Mycolicibacter engbaekii',
 '36809': 'Mycobacteroides abscessus',
 '2077092': 'Nocardia suismassiliense',
 '2835306': 'Mycolicibacter acidiphilus',
 '37333': 'Nocardia transvalensis',
 '996641': 'Kribbella amoyensis',
 '2034511': 'Mycobacterium palauense',
 '1112204': 'Gordonia polyisoprenivorans VH2',
 '263849': 'Rhodococcus phenolicus',
 '1121927': 'Gordonia hirsuta DSM 44140 = NBRC 16056',
 '39692': 'Mycolicibacterium parafortuitum',
 '543736': 'Rhodococcus opacus PD630',
 '1210100': 'Nocardia uniformis NBRC 13702',
 '81858': 'Mycolicibacterium elephantis',
 '1206735': 'Nocardia takedensis NBRC 100417',
 '36813': 'Mycolicibacterium pulveris',
 '1249101': 'Mycolicibacterium celeriflavum',
 '2873381': 'Nocardia coffeae',
 '2758710': 'Gordonia jinghuaiqii',
 '1538463': 'Nocardia donostiensis',
 '85044': 'Williamsia muralis',
 '2943705': 'Nocardia sputi',
 '1210073': 'Nocardia salmonicida subsp. cummidelens NBRC 100378',
 '885042': 'Williamsia phyllosphaerae',
 '1792': 'Mycolicibacterium chitae',
 '145285': 'Nocardia ignorata',
 '1520670': '[Mycobacterium] stephanolepidis',
 '1210098': 'Nocardia vaccinii NBRC 15922',
 '2911516': 'Gordonia zhenghanii',
 '39122': 'Skermania piniformis',
 '455432': 'Nocardia terpenica',
 '37326': 'Nocardia brasiliensis',
 '2545757': 'Prescottella subtropica',
 '2879464': 'Rhodococcus yananensis',
 '168276': 'Rhodococcus tukisamuensis',
 '208602': 'Nocardia puris',
 '2144174': 'Nocardia aurea',
 '2911517': 'Gordonia liuliyuniae',
 '209247': 'Nocardia yamanashiensis',
 '85968': 'Mycolicibacterium brumae',
 '1572660': 'Kribbella speibonae',
 '2545717': 'Nocardia colli',
 '223392': 'Rhodococcus gordoniae',
 '1578165': 'Mycobacteroides saopaulense',
 '480036': 'Nocardia blacklockiae',
 '2799499': 'Antrihabitans stalagmiti',
 '408066': 'Aldersonia kunmingensis',
 '1210094': 'Nocardia speluncae NBRC 108251',
 '279262': 'Nocardia mexicana',
 '1210092': 'Nocardia sienata NBRC 100364',
 '1223546': 'Nocardia grenadensis NBRC 108939',
 '1210078': 'Nocardia kruczakiae NBRC 101016',
 '1223542': 'Gordonia malaquae NBRC 108250',
 '1323361': 'Prescottella defluvii',
 '99653': 'Rhodococcus koreensis',
 '37328': 'Nocardia carnea',
 '1215925': 'Nocardia bhagyanarayanae',
 '1771': 'Mycolicibacterium phlei',
 '2585199': 'Nocardia aurantia',
 '2878563': 'Nocardia rosealba',
 '2842303': 'Nocardia albiluteola',
 '1210069': 'Nocardia coubleae NBRC 108252',
 '1210065': 'Nocardia anaemiae NBRC 100462',
 '1206731': 'Nocardia jiangxiensis NBRC 101359',
 '2760083': 'Tomitella gaofuii',
 '2749991': 'Nocardia gipuzkoensis',
 '364929': 'Williamsia soli',
 '1141657': 'Nocardia vulneris',
 '1206730': 'Nocardia higoensis NBRC 100133',
 '2811421': 'Rhodococcus pseudokoreensis',
 '204891': 'Nocardia iowensis',
 '83262': 'Mycobacteroides immunogenum',
 '1136941': 'Gordonia phthalatica',
 '134984': 'Nocardia fluminea',
 '2815722': 'Nocardia noduli',
 '1387982': 'Tomitella cavernea',
 '2675851': 'Nocardia terrae',
 '1788': 'Mycolicibacter terrae',
 '1219030': 'Rhodococcus zopfii NBRC 100606 = JCM 9919',
 '1223549': 'Nocardia fusca NBRC 14340',
 '44752': 'Rhodococcus wratislaviensis',
 '1210077': 'Nocardia inohanensis NBRC 100128',
 '1210084': 'Nocardia miyunensis NBRC 108239',
 '1210062': 'Nocardia acidivorans NBRC 108247',
 '53428': 'Nocardia crassostreae',
 '2546320': 'Rhodococcus spelaei',
 '1220553': 'Nocardia flavorosea NBRC 108225',
 '85688': 'Nocardia cerradoensis',
 '1206720': 'Nocardia aobensis NBRC 100429',
 '1206739': 'Nocardia testacea NBRC 100365',
 '2605429': 'Hoyosella suaedae',
 '38301': 'Corynebacterium minutissimum',
 '756689': 'Nocardia amikacinitolerans',
 '2785916': 'Nocardia bovistercoris',
 '184756': 'Nocardia caishijiensis',
 '2575441': 'Kribbella jiaozuonensis',
 '300028': 'Rhodococcus triatomae',
 '1824': 'Nocardia asteroides',
 '1437874': 'Corynebacterium sphenisci DSM 44792',
 '2213200': 'Nocardia mangyaensis',
 '1460372': 'Mycobacteroides chelonae CCUG 47445',
 '247156': 'Nocardia farcinica IFM 10152',
 '1210101': 'Nocardia xishanensis NBRC 101358',
 '1210083': 'Nocardia lijiangensis NBRC 108240',
 '1210088': 'Nocardia jejuensis NBRC 103114',
 '45979': 'Nocardia pseudobrasiliensis',
 '1223544': 'Gordonia sihwensis NBRC 108236',
 '2755382': 'Nocardia huaxiensis',
 '521096': 'Tsukamurella paurometabola DSM 20162',
 '1691570': 'Nocardia rhizosphaerihabitans',
 '1990687': 'Rhodococcus oxybenzonivorans',
 '2736643': 'Nocardia barduliensis',
 '135487': 'Nocardia cyriacigeorgica',
 '225051': 'Nocardia alba',
 '2358193': 'Mycolicibacterium stellerae',
 '1223489': 'Nocardia niwae NBRC 108934 = DSM 45340',
 '1206742': 'Nocardia vinacea NBRC 16497',
 '1206722': 'Nocardia araoensis NBRC 100135',
 '2495913': 'Rhodococcus cavernicola',
 '1206743': 'Nocardia veterana NBRC 100344',
 '1206734': 'Nocardia paucivorans NBRC 100373',
 '443218': 'Hoyosella subflava DQS3-9A1',
 '72806': 'Williamsia maris',
 '2483361': 'Nocardia stercoris',
 '1210061': 'Nocardia africana NBRC 100379',
 '37330': 'Nocardia nova',
 '1210087': 'Nocardia shimofusensis NBRC 100134',
 '1210068': 'Nocardia beijingensis NBRC 16342',
 '1210064': 'Nocardia altamirensis NBRC 108246',
 '1210067': 'Nocardia arthritidis NBRC 100137',
 '1210079': 'Nocardia gamkensis NBRC 108242',
 '1206721': 'Nocardia asiatica NBRC 100129',
 '1206723': 'Nocardia abscessus NBRC 100374',
 '2585198': 'Nocardia macrotermitis',
 '2762214': 'Corynebacterium gallinarum',
 '1210096': 'Nocardia vermiculata NBRC 100427',
 '2765363': 'Corynebacterium meridianum',
 '1206729': 'Nocardia exalbida NBRC 100660',
 '1206725': 'Nocardia brevicatena NBRC 12119',
 '1105143': 'Kribbella shirazensis',
 '182080': 'Actinomadura namibiensis',
 '1004901': 'Gordonia iterans',
 '196164': 'Corynebacterium efficiens YS-314',
 '2742202': 'Hoyosella lacisalsi',
 '1219361': 'Millisia brevis NBRC 105863',
 '84724': 'Lentzea waywayandensis',
 '1686286': 'Corynebacterium phoceense',
 '1993': 'Actinomadura madurae',
 '2800405': 'Corynebacterium antarcticum',
 '2905831': 'Pseudonocardia terrae',
 '1210071': 'Nocardia elegans NBRC 108235',
 '1348662': 'Corynebacterium argentoratense DSM 44202',
 '239498': 'Tsukamurella pseudospumae',
 '1970234': 'Tsukamurella ocularis',
 '2340916': 'Nocardia panacis',
 '564415': 'Herbidospora sakaeratensis',
 '37331': 'Pseudonocardia petroleophila',
 '2724524': 'Amycolatopsis acididurans',
 '531938': 'Lentzea atacamensis',
 '1616106': 'Nocardia camponoti',
 '60450': 'Kribbella sandramycini',
 '402600': 'Lentzea xinjiangensis',
 '479435': 'Kribbella flavida DSM 17836',
 '2864039': 'Actinomadura parmotrematis',
 '1206740': 'Nocardia thailandica NBRC 100428',
 '1068980': 'Amycolatopsis nigrescens CSC17Ta-90',
 '1124744': 'Kribbella sindirgiensis',
 '2592068': 'Tsukamurella conjunctivitidis',
 '2575442': 'Herbidospora galbida',
 '1128675': 'Pseudonocardia kujensis',
 '28444': 'Herbidospora cretacea',
 '1220583': 'Gordonia aichiensis NBRC 108223',
 '1200352': 'Corynebacterium terpenotabidum Y-11',
 '416017': 'Kribbella aluminosa',
 '2604572': 'Actinomadura decatromicini',
 '360086': 'Lentzea kentuckyensis',
 '391736': 'Williamsia serinedens',
 '236068': 'Kribbella jejuensis',
 '1123258': 'Smaragdicoccus niigatensis DSM 44881 = NBRC 103563',
 '2530375': 'Kribbella turkmenica',
 '1220561': 'Actinomadura kijaniata NBRC 14229',
 '664692': 'Amycolatopsis pithecellobii',
 '547056': 'Actinokineospora baliensis',
 '630975': 'Pseudonocardia kunmingensis',
 '2795733': 'Qaidamihabitans albus',
 '103732': 'Lentzea flava',
 '1223511': 'Pseudonocardia sulfidoxydans NBRC 16205',
 '2200761': 'Lentzea terrae',
 '1122138': 'Kribbella catacumbae DSM 19601',
 '40571': 'Lentzea albidocapillata',
 '1816684': 'Corynebacterium pacaense',
 '571913': 'Luteipulveratus mongoliensis',
 '1120937': 'Actinomadura rifamycini DSM 43936',
 '2508997': 'Actinomadura soli',
 '2736640': 'Pseudonocardia broussonetiae',
 '2792013': 'Pseudonocardia oceani',
 '369936': 'Arthrobacter alkaliphilus',
 '641025': 'Lentzea jiangxiensis',
 '1586287': 'Lentzea guizhouensis',
 '1048339': 'Sporichthya polymorpha DSM 43042',
 '295585': 'Herbidospora daliensis',
 '1121368': 'Corynebacterium pseudodiphtheriticum DSM 44287',
 '446462': 'Actinosynnema mirum DSM 43827',
 '200379': 'Lentzea flaviverrucosa',
 '675635': 'Pseudonocardia dioxanivorans CB1190',
 '111802': 'Actinomadura fibrosa',
 '236067': 'Kribbella solani',
 '479432': 'Streptosporangium roseum DSM 43021',
 '909613': 'Actinokineospora spheciospongiae',
 '2020703': 'Lentzea cavernae',
 '2592067': 'Tsukamurella asaccharolytica',
 '83302': 'Microbispora corallina',
 '2591470': 'Lentzea tibetensis',
 '543632': 'Actinoplanes subtropicus',
 '42197': 'Actinosynnema pretiosum',
 '1431546': 'Corynebacterium aquilae DSM 44791',
 '2654637': 'Actinokineospora pegani',
 '1219029': 'Rhodococcus yunnanensis NBRC 103083',
 '58123': 'Spirillospora albida',
 '1365924': 'Kibdelosporangium banguiense',
 '60706': 'Actinomadura formosensis',
 '2893887': 'Actinomycetospora soli',
 '65499': 'Lentzea albida',
 '2185285': 'Kribbella monticola',
 '108486': 'Corynebacterium falsenii',
 '2030': 'Kibdelosporangium aridum',
 '1220564': 'Actinomadura macra NBRC 14102',
 '571190': 'Saccharothrix saharensis',
 '1123023': 'Pseudonocardia acaciae DSM 45401',
 '705336': 'Actinomadura darangshiensis',
 '1280637': 'Saccharothrix carnea',
 '558173': 'Corynebacterium doosanense CAU 212 = DSM 45436',
 '2750812': 'Actinomadura graeca',
 '882446': 'Nocardia goodfellowii',
 '1727': 'Corynebacterium variabile',
 '1105145': 'Saccharothrix ecbatanensis',
 '683150': 'Arthrobacter nitrophenolicus',
 '1266829': 'Kribbella albertanoniae',
 '1654476': 'Umezawaea endophytica',
 '1540520': 'Kribbella italica',
 '2576905': 'Microbispora fusca',
 '35755': 'Corynebacterium kutscheri',
 '106370': 'Frankia casuarinae',
 '79909': 'Actinomadura livida',
 '95160': 'Actinomadura catellatispora',
 '1128676': 'Pseudonocardia hierapolitana',
 '485602': 'Actinophytocola xinjiangensis',
 '33919': 'Saccharothrix coeruleofusca',
 '76726': 'Pseudonocardia hydrocarbonoxydans',
 '2320431': 'Corynebacterium silvaticum',
 '1089545': 'Amycolatopsis balhimycina FH 1894',
 '931089': 'Corynebacterium deserti GIMN1.010',
 '1677852': 'Microbispora camponoti',
 '1220567': 'Actinomadura rubrobrunea NBRC 15275',
 '1562887': 'Frankia coriariae',
 '452863': 'Pseudarthrobacter chlorophenolicus A6',
 '2761101': 'Nocardioides luti',
 '860235': 'Kibdelosporangium phytohabitans',
 '1045776': 'Kutzneria buriramensis',
 '161355': 'Planomonospora sphaerica',
 '1848329': 'Nonomuraea diastatica',
 '280293': 'Catenulispora rubra'}

In [20]:
df['scomnames'].unique()

drop = ['Mycobacterium malmoense',
 'Mycobacterium frederiksbergens',
 'Mycolicibacterium vinylchloridicum',
 'Mycobacterium seoulense',
 'Mycobacterium asiaticum DSM 44297',
 'Mycobacterium simulans',
 'Mycolicibacterium anyangense',
 'Mycobacterium cookii',
 'Mycolicibacterium hippocampi',
 'Mycobacterium conspicuum'
]

In [21]:
df.head()

,sseqid,evalue,bitscore,pident,length,staxid,scomnames,ssciname,sblastnames,sseq,genus
0,gi|448814763|ref|NC_000962.3|,3.270000e-118,434.0,100.000,240,83332,Mycobacterium tuberculosis H37Rv,Mycobacterium tuberculosis H37Rv,high G+C Gram-positive bacteria,ATGGTGGAAATCGTGGCTGGAAAACAACGCGCTCCGGTCGCTGCCG...,Mycobacterium
1,gi|340625033|ref|NC_015848.1|,1.390000e-116,429.0,99.583,240,1048245,Mycobacterium canettii CIPT 140010059,Mycobacterium canettii CIPT 140010059,high G+C Gram-positive bacteria,ATGGTGGAAATCGTGGCTGGAAAACAACGCGCTCCGGTCGCTGCCG...,Mycobacterium
2,gi|1816737860|ref|NZ_AP022575.1|,7.710000e-82,314.0,89.496,238,398694,Mycobacterium shinjukuense,Mycobacterium shinjukuense,high G+C Gram-positive bacteria,GGTGGAGA-CGTGGCTGGAAAACAAGACGCTCCGGTCACTGCCGGC...,Mycobacterium
3,gi|1912148917|ref|NZ_OCVX01000007.1|,3.280000e-61,244.0,82.979,235,627089,Mycobacterium simulans,Mycobacterium simulans,high G+C Gram-positive bacteria,GGACATCATGGCTGGAAACCTGGGCGCTCCCGTCGCCGCCGGCGTC...,Mycobacterium
4,gi|1063562954|ref|NZ_MIHB01000001.1|,4.870000e-59,237.0,82.684,231,28445,Mycobacterium intermedium,Mycobacterium intermedium,high G+C Gram-positive bacteria,ATCGTGGTTGCAAACCTGGGCGCTCCGGTCGGTGCCGGGGTGTACA...,Mycobacterium

In [22]:
df = df[~df['scomnames'].isin(drop)]

In [23]:
df = df[~df['staxid'].duplicated()]

In [24]:
df.shape

(484, 11)

In [26]:
t = []
for record in SeqIO.parse("23may2023/bspa_blast_hit_23May_muscle.mfa.fasta", "fasta"):    
    seqs.append(record)

Empty DataFrame
Columns: [sseqid, evalue, bitscore, pident, length, staxid, scomnames, ssciname, sblastnames, sseq, genus]
Index: []

In [199]:
sequences = []

for i in df.index:
    sequences.append(SeqRecord(Seq(df.loc[i, 'sseq']), id=df.loc[i,'staxid'].astype(str), description=""))

In [200]:
with open("blastn_bspa_hits_23May2023.fasta", "w") as output_handle:
    SeqIO.write(sequences, output_handle, "fasta")

In [26]:
# filename = "database_species"

# with open(filename) as f:
#     species = f.readlines()

In [27]:
# species

In [108]:
txid = "1077976 1034768 526226 1041514 1219361 1223536 1349764 1223524 910954 1077144 521096 1219362 65509 1051973 1443897 1443899 935266 1219024 1240349 1302251 1136179 1303690 37326 37329 37330 1206728 1006579 1408268 945712 1087451 1089446 681645 698970 1206106 246196 1150599 710421 1354275 710685 1087053 1226753 1341646 1305860 1798 1069221 1788 723879 443218 2038731 1460372 1335416 1308742 1166017 272631 1297123 1778 459428 410289 757419 757419 757418 1402213 1299330 675635 1123023 699434 2670332 1123026 713604 1382595 882083 928729 33921 285531 1412146 285575 1203460 1169414 1245473 1348637 1160710 1348634 1284679 1227262 1216973 1302660 136927 704114 512565 1408351 999546 1121926 446470 1388259 904794 1157400 1318715 1318715 531853 1236904 662947 450201 479703"

txid.replace(" ", ",")

'1077976,1034768,526226,1041514,1219361,1223536,1349764,1223524,910954,1077144,521096,1219362,65509,1051973,1443897,1443899,935266,1219024,1240349,1302251,1136179,1303690,37326,37329,37330,1206728,1006579,1408268,945712,1087451,1089446,681645,698970,1206106,246196,1150599,710421,1354275,710685,1087053,1226753,1341646,1305860,1798,1069221,1788,723879,443218,2038731,1460372,1335416,1308742,1166017,272631,1297123,1778,459428,410289,757419,757419,757418,1402213,1299330,675635,1123023,699434,2670332,1123026,713604,1382595,882083,928729,33921,285531,1412146,285575,1203460,1169414,1245473,1348637,1160710,1348634,1284679,1227262,1216973,1302660,136927,704114,512565,1408351,999546,1121926,446470,1388259,904794,1157400,1318715,1318715,531853,1236904,662947,450201,479703'

In [109]:
txlist = txid.split(" ")
txlist = pd.Series(txlist).astype(int).tolist()

txlist[:5]

[1077976, 1034768, 526226, 1041514, 1219361]

In [30]:
df = pd.read_csv("ncbi_taxid_reference/fullnamelineage.dmp", delimiter="\t")

df = df[['1', 'root', 'Unnamed: 4']]
df.columns = ['taxid', 'root', 'data']

In [31]:
df

,taxid,root,data
0,131567,cellular organisms,NaN
1,2157,Archaea,cellular organisms;
2,1935183,Asgard group,cellular organisms; Archaea;
3,2798909,Candidatus Baldrarchaeota,cellular organisms; Archaea; Asgard group;
4,2798916,Candidatus Baldrarchaeia,cellular organisms; Archaea; Asgard group; Can...
...,...,...,...
2501331,2413,Transposon Tn7,other entries; other sequences; transposons;
2501332,2417,Transposon Tn9,other entries; other sequences; transposons;
2501333,2414,Transposon Tn903,other entries; other sequences; transposons;
2501334,2415,Transposon Tn916,other entries; other sequences; transposons;
2501335,2416,Transposon Tn917,other entries; other sequences; transposons;

In [30]:
subset = df[df['taxid'].isin(txlist)]

subset[['phylum', 'genus', 'species', 'subsp']] = subset['data'].str.split(";", expand=True)[[3, 7, 8, 9]]
subset.loc[ (subset['subsp'] != " ") & ~(subset['subsp'].isna()), 'species'] = subset.loc[ (subset['subsp'] != " ") & ~(subset['subsp'].isna()), 'subsp']

In [70]:
subset['genus'].str.split(" ", expand=True)[1].unique().tolist()

['Escherichia',
 'Actinomyces',
 'Glycomyces',
 'Stackebrandtia',
 'Streptomyces',
 'Microbacterium',
 'Arthrobacter',
 'Actinoplanes',
 'Micromonospora',
 'Salinispora',
 'Corynebacterium',
 'Dietzia',
 'Gordonia',
 'Millisia',
 'Skermania',
 'Hoyosella',
 'Mycobacterium',
 'Mycobacteroides',
 'Mycolicibacillus',
 'Mycolicibacter',
 'Mycolicibacterium',
 'Nocardia',
 'Parvopolyspora',
 'Rhodococcus',
 'Williamsia',
 'Tsukamurella',
 'Amycolatopsis',
 'Pseudonocardia',
 'Saccharomonospora',
 'Saccharopolyspora',
 'Saccharothrix',
 'Nocardiopsis',
 'Thermobifida',
 'Staphylococcus',
 'Enterococcus',
 'Nostocaceae',
 'Mycoplasmoides']

In [77]:
dfb = pd.read_csv("protein_cluster_search_taxid_file.txt", delimiter=";")
dfb.columns = ['misc', 'taxid']

In [88]:
taxid2 = dfb['taxid'].str.strip("actb. \t").unique().astype(int)

In [96]:
subset2 = df[df['taxid'].isin(taxid2)]

subset2[['phylum', 'genus', 'species', 'subsp']] = subset2['data'].str.split(";", expand=True)[[3, 7, 8, 9]]
subset2.loc[ (subset2['subsp'] != " ") & ~(subset2['subsp'].isna()), 'species'] = subset2.loc[ 
    (subset2['subsp'] != " ") & ~(subset2['subsp'].isna()), 'subsp']

In [113]:
# subset2.drop_duplicates(subset='genus')['taxid'].tolist()

In [114]:
txlist2 = txlist + subset2.drop_duplicates(subset='genus')['taxid'].tolist()

In [123]:
",".join(pd.Series(txlist2).drop_duplicates().astype(str).tolist())

'1077976,1034768,526226,1041514,1219361,1223536,1349764,1223524,910954,1077144,521096,1219362,65509,1051973,1443897,1443899,935266,1219024,1240349,1302251,1136179,1303690,37326,37329,37330,1206728,1006579,1408268,945712,1087451,1089446,681645,698970,1206106,246196,1150599,710421,1354275,710685,1087053,1226753,1341646,1305860,1798,1069221,1788,723879,443218,2038731,1460372,1335416,1308742,1166017,272631,1297123,1778,459428,410289,757419,757418,1402213,1299330,675635,1123023,699434,2670332,1123026,713604,1382595,882083,928729,33921,285531,1412146,285575,1203460,1169414,1245473,1348637,1160710,1348634,1284679,1227262,1216973,1302660,136927,704114,512565,1408351,999546,1121926,446470,1388259,904794,1157400,1318715,531853,1236904,662947,450201,479703,1911520,977794,1508375,134849,1469144,516124,2706034,203263,499555,36820,1121721,264148,39122,616997,2742202,1762,2943498,36809,1069220,342002,36811,2448780,408066,2584121,120957,1644129,191292,359359,321325,2072582,286802,2592067,630403,913944,546364,1931992,75291,1892852,1490222,1679523,58123'

In [101]:
df

,taxid,root,data
0,131567,cellular organisms,NaN
1,2157,Archaea,cellular organisms;
2,1935183,Asgard group,cellular organisms; Archaea;
3,2798909,Candidatus Baldrarchaeota,cellular organisms; Archaea; Asgard group;
4,2798916,Candidatus Baldrarchaeia,cellular organisms; Archaea; Asgard group; Can...
...,...,...,...
2501331,2413,Transposon Tn7,other entries; other sequences; transposons;
2501332,2417,Transposon Tn9,other entries; other sequences; transposons;
2501333,2414,Transposon Tn903,other entries; other sequences; transposons;
2501334,2415,Transposon Tn916,other entries; other sequences; transposons;
2501335,2416,Transposon Tn917,other entries; other sequences; transposons;